app = "clean-housekeeper-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "python main.py"

# ❗ ВАЖНО: НИКАКИХ http_service
# ❗ НИКАКИХ checks
